/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as React19RouteImport } from './routes/react-19'
import { Route as IndexRouteImport } from './routes/index'

const React19Route = React19RouteImport.update({
  id: '/react-19',
  path: '/react-19',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/react-19': typeof React19Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/react-19': typeof React19Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/react-19': typeof React19Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/react-19'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/react-19'
  id: '__root__' | '/' | '/react-19'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  React19Route: typeof React19Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/react-19': {
      id: '/react-19'
      path: '/react-19'
      fullPath: '/react-19'
      preLoaderRoute: typeof React19RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  React19Route: React19Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
