export const staticServices = [
  {
    id: 'cdn-react-17',
    packageName: '@empjs/cdn-react',
    packageDir: 'packages/cdn-react-17',
    root: 'packages/cdn-react-17/dist',
    port: 1700,
    cors: true,
    groups: ['cdn', 'react-runtime'],
    assets: {
      development: 'reactRouter.development.umd.js',
      production: 'reactRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-react-18',
    packageName: '@empjs/cdn-react',
    packageDir: 'packages/cdn-react-18',
    root: 'packages/cdn-react-18/dist',
    port: 1800,
    cors: true,
    groups: ['cdn', 'react-runtime'],
    assets: {
      development: 'reactRouter.development.umd.js',
      production: 'reactRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-react-19',
    packageName: '@empjs/cdn-react',
    packageDir: 'packages/cdn-react-19',
    root: 'packages/cdn-react-19/dist',
    port: 1900,
    cors: true,
    groups: ['cdn', 'react-runtime'],
    assets: {
      development: 'reactRouter.development.umd.js',
      production: 'reactRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-react-wouter',
    packageName: '@empjs/cdn-react-wouter',
    packageDir: 'packages/cdn-react-wouter',
    root: 'packages/cdn-react-wouter/dist',
    port: 2200,
    cors: true,
    groups: ['cdn', 'react-router'],
    assets: {
      development: 'reactRouter.development.umd.js',
      production: 'reactRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-react-tanstack',
    packageName: '@empjs/cdn-react-tanstack',
    packageDir: 'packages/cdn-react-19-tanstack-router',
    root: 'packages/cdn-react-19-tanstack-router/dist',
    port: 2200,
    cors: true,
    groups: ['cdn', 'react-router'],
    assets: {
      development: 'reactRouter.development.umd.js',
      production: 'reactRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-vue-2',
    packageName: '@empjs/cdn-vue',
    packageDir: 'packages/cdn-vue-2',
    root: 'packages/cdn-vue-2/dist',
    port: 2200,
    cors: true,
    groups: ['cdn', 'vue-runtime'],
    assets: {
      development: 'vueRouter.development.umd.js',
      production: 'vueRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-vue-3',
    packageName: '@empjs/cdn-vue',
    packageDir: 'packages/cdn-vue-3',
    root: 'packages/cdn-vue-3/dist',
    port: 2300,
    cors: true,
    groups: ['cdn', 'vue-runtime'],
    assets: {
      development: 'vueRouter.development.umd.js',
      production: 'vueRouter.production.umd.js',
    },
  },
  {
    id: 'cdn-vue-router-pinia',
    packageName: '@empjs/cdn-vue-router-pinia',
    packageDir: 'packages/cdn-vue-router-pinia',
    root: 'packages/cdn-vue-router-pinia/dist',
    port: 2300,
    cors: true,
    groups: ['cdn', 'vue-runtime'],
    assets: {
      development: 'vueRouter.development.umd.js',
      production: 'vueRouter.production.umd.js',
    },
  },
  {
    id: 'lib-react-17',
    packageName: '@empjs/lib-react',
    packageDir: 'packages/lib-react-17',
    root: 'packages/lib-react-17/dist',
    port: 1700,
    cors: true,
    groups: ['lib'],
    assets: {
      development: 'runtime.umd.js',
      production: 'runtime.umd.js',
    },
  },
  {
    id: 'lib-vue-2',
    packageName: '@empjs/lib-vue',
    packageDir: 'packages/lib-vue-2',
    root: 'packages/lib-vue-2/dist',
    port: 1800,
    cors: true,
    groups: ['lib'],
    assets: {
      development: 'runtime.umd.js',
      production: 'runtime.umd.js',
    },
  },
  {
    id: 'emp-share',
    packageName: '@empjs/share',
    packageDir: 'packages/emp-share',
    root: 'packages/emp-share/output',
    port: 2100,
    cors: true,
    groups: ['runtime', 'react-runtime', 'vue-runtime'],
    assets: {
      development: 'sdk.js',
      production: 'sdk.js',
    },
  },
  {
    id: 'emp-polyfill',
    packageName: '@empjs/polyfill',
    packageDir: 'packages/emp-polyfill',
    root: 'packages/emp-polyfill/dist',
    port: 9011,
    cors: true,
    groups: ['runtime', 'polyfill'],
    assets: {
      development: 'es.js',
      production: 'es.js',
    },
  },
]
