// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ATable: typeof import('ant-design-vue/es')['Table']
    ButtonComponent: typeof import('./src/components/ButtonComponent.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    TsxScript: typeof import('./src/components/TsxScript.vue')['default']
  }
}

export { }
